/* eslint-disable */
/**
 * GENERATED from docs/rebuild/JJB-phase-2a-url-inventory.csv
 * by scripts/generate-migration-ledger.mjs — do not edit by hand.
 */
export const inventoryRedirects: Record<string, string> = {
  "/10-000-hours-just-start": "/blogs/blog/10-000-hours-just-start",
  "/5-ways-jiujitsu-benefits-children-autism": "/blogs/blog/5-ways-jiujitsu-benefits-children-autism",
  "/a-coach-is-more-than-just-a-teacher": "/blogs/blog/a-coach-is-more-than-just-a-teacher",
  "/a-deeper-understanding-of-jiu-jitsu": "/blogs/blog/a-deeper-understanding-of-jiu-jitsu",
  "/a-jiu-jitsu-experience": "/blogs/blog/a-jiu-jitsu-experience",
  "/about": "/pages/about",
  "/about/organisation": "/pages/about",
  "/academies": "/pages/jiu-jitsu-brotherhood-club-network",
  "/affiliate-disclosure": "/pages/disclaimer",
  "/become-a-master-of-escapes": "/blogs/blog/become-a-master-of-escapes",
  "/beginners-guide-bjj": "/pages/beginners-guide-to-bjj-signup",
  "/beginners-guide-bjj-2": "/pages/beginners-guide-to-bjj-signup",
  "/bjjs-biggest-weakness-is-its-new-secret-weapon": "/blogs/blog/bjjs-biggest-weakness-is-its-new-secret-weapon",
  "/blog": "/pages/blog",
  "/brazilian-jiu-jitsu-competitions": "/blogs/blog/brazilian-jiu-jitsu-competitions",
  "/collections/enso-3-0": "/collections/gis",
  "/contact": "/pages/contact",
  "/control-your-breathing": "/blogs/blog/control-your-breathing",
  "/copyright-notice": "/pages/terms-conditions",
  "/cross-training-in-wrestling-and-jiu-jitsu": "/blogs/blog/cross-training-in-wrestling-and-jiu-jitsu",
  "/cut-weight-jiu-jitsu-competitions": "/blogs/blog/cut-weight-jiu-jitsu-competitions",
  "/disclaimer": "/pages/disclaimer",
  "/eddie-bravo-a-jiu-jitsu-original": "/blogs/blog/eddie-bravo-a-jiu-jitsu-original",
  "/family-jiu-jitsu": "/blogs/blog/family-jiu-jitsu",
  "/gi-or-no-gi": "/blogs/blog/gi-or-no-gi",
  "/grappling-martial-arts": "/blogs/blog/grappling-martial-arts",
  "/how-jiu-jitsu-works": "/pages/beginners-guide-to-bjj-signup",
  "/how-to-learn-jiu-jitsu-faster": "/blogs/blog/how-to-learn-jiu-jitsu-faster",
  "/importance-footwork-jiu-jitsu": "/blogs/blog/importance-footwork-jiu-jitsu",
  "/important-tips-for-beginners": "/blogs/blog/important-tips-for-beginners",
  "/jiu-jitsu-better-dieting": "/blogs/blog/jiu-jitsu-better-dieting",
  "/jiu-jitsu-brotherhood-affiliation": "/pages/jiu-jitsu-brotherhood-club-network",
  "/joint-locks-in-jiu-jitsu": "/blogs/blog/joint-locks-in-jiu-jitsu",
  "/leg-locks-101": "/blogs/blog/leg-locks-101",
  "/main-positions-jiu-jitsu": "/blogs/blog/main-positions-jiu-jitsu",
  "/martial-arts-styles": "/blogs/blog/martial-arts-styles",
  "/mobility-training-for-jiu-jitsu": "/blogs/blog/mobility-training-for-jiu-jitsu",
  "/news": "/blogs/blog",
  "/no-you-didnt-start-jiu-jitsu-too-late": "/blogs/blog/no-you-didnt-start-jiu-jitsu-too-late",
  "/organisation": "/pages/about",
  "/pages/bjj-in-kingston-upon-thames": "https://www.kingstonjiujitsu.com/",
  "/pages/ccpa-opt-out": "/pages/privacy-policy",
  "/pages/copyright-notice": "/pages/terms-conditions",
  "/pages/home": "/",
  "/pages/test-page": "/blogs/blog/no-bad-positions-in-jiu-jitsu",
  "/pareto-principle-for-jiu-jitsu": "/blogs/blog/pareto-principle-for-jiu-jitsu",
  "/policies/privacy-policy": "/pages/privacy-policy",
  "/policies/refund-policy": "/pages/terms-conditions",
  "/policies/terms-of-service": "/pages/terms-conditions",
  "/positional-study-shin-to-shin-single-leg-x-ashi-garami": "/blogs/blog/positional-study-shin-to-shin-single-leg-x-ashi-garami",
  "/privacy-policy": "/pages/privacy-policy",
  "/private-instruction": "/pages/contact",
  "/products/copy-of-brotherhood-belt": "/products/journey-bjj-belt",
  "/products/sticker-pack": "/collections/patches",
  "/progression-the-belt-system": "/pages/progression-the-belt-system",
  "/rickson-gracie-jiu-jitsus-living-legend": "/blogs/blog/rickson-gracie-jiu-jitsus-living-legend",
  "/roger-gracie": "/blogs/blog/roger-gracie",
  "/shipping-and-returns-policy": "/pages/terms-conditions",
  "/shipping-and-returns-policy-pjj": "/pages/terms-conditions",
  "/shipping-returns-policy-2": "/pages/terms-conditions",
  "/shop": "/collections/all",
  "/sleep-and-the-jiu-jitsu-practitioner": "/blogs/blog/sleep-and-the-jiu-jitsu-practitioner",
  "/starting-brazilian-jiu-jitsu": "/pages/beginners-guide-to-bjj-signup",
  "/starting-brazilian-jiu-jitsu/a-brief-history-of-jiu-jitsu": "/blogs/blog/a-brief-history-of-bjj",
  "/starting-brazilian-jiu-jitsu/a-typical-class": "/blogs/blog/attending-your-first-jiu-jitsu-class",
  "/starting-brazilian-jiu-jitsu/introduction": "/pages/beginners-guide-to-bjj-signup",
  "/starting-brazilian-jiu-jitsu/matt-etiquette": "/blogs/blog/jiu-jitsu-mat-etiquette",
  "/starting-brazilian-jiu-jitsu/where-to-train": "/pages/beginners-guide-to-bjj-signup",
  "/support-us": "/pages/about",
  "/terms-of-use": "/pages/terms-conditions",
  "/testimonials": "/pages/about",
  "/the-bjj-blue-belt-test-full": "/pages/progression-the-belt-system",
  "/the-evolution-of-jiu-jitsu": "/blogs/blog/the-evolution-of-jiu-jitsu",
  "/the-gracies-first-family-of-jiu-jitsu": "/blogs/blog/the-gracies-first-family-of-jiu-jitsu",
  "/the-rear-naked-choke-the-king-of-submissions": "/blogs/blog/the-rear-naked-choke-the-king-of-submissions",
  "/the-science-of-jiu-jitsu": "/blogs/blog/the-science-of-jiu-jitsu",
  "/the-single-leg-takedown-a-conceptual-approach": "/blogs/blog/the-single-leg-takedown-a-conceptual-approach",
  "/the-top-7-shoulder-conditions-effecting-grapplers": "/blogs/blog/the-top-7-shoulder-conditions-effecting-grapplers",
  "/understanding-takedowns-in-jiu-jitsu": "/blogs/blog/understanding-takedowns-in-jiu-jitsu",
  "/using-your-minds-eye-visualization-for-jiu-jitsu": "/blogs/blog/using-your-minds-eye-visualization-for-jiu-jitsu",
  "/why-concepts-are-better-than-techniques-in-bjj": "/blogs/blog/why-concepts-are-better-than-techniques-in-bjj",
  "/why-you-should-compete-at-least-once-in-bjj": "/blogs/blog/why-you-should-compete-at-least-once-in-bjj",
  "/wrestling-takedowns": "/blogs/blog/wrestling-takedowns",
  "/yoga-jiu-jitsu-a-natural-symbiosis": "/blogs/blog/yoga-jiu-jitsu-a-natural-symbiosis",
};

export const inventoryGone: string[] = [
  "/3-phase-arm-lock-from-closed-guard",
  "/3-unusual-ways-to-open-the-guard",
  "/4-jiu-jitsu-lessons-from-bruce-lee",
  "/5-reasons-kettlebells-are-the-perfect-compliment-to-jiu-jitsu",
  "/6-unusual-ways-improve-jiu-jitsu",
  "/7-reasons-your-jiu-jitsu-isnt-getting-better",
  "/8-basic-skills-for-jiu-jitsu",
  "/8-steps-to-finding-the-perfect-bjj-gi",
  "/8-tips-for-grappling-after-30",
  "/8-tips-to-instantly-improve-your-guard",
  "/90-degree-rule",
  "/a-detailed-guide-to-the-guillotine-choke",
  "/a-parents-guide-to-bjj-for-kids",
  "/a-simple-effective-guard-pass",
  "/a-simple-workout-for-grappling-jiu-jitsu",
  "/academic-draft",
  "/awareness-and-the-jiu-jitsu-fighter",
  "/basic-guard-passing-drills",
  "/basics-of-the-straight-foot-lock",
  "/beat-half-guard-knee-shield",
  "/become-an-affiliate",
  "/beginners-read-first-bjj-class",
  "/berimbolo-cant-save-you",
  "/better-jiu-jitsu-in-28-days-challenge",
  "/bjj-blue-belt-test",
  "/bjj-concept-control-the-head",
  "/bjj-gym-bag-hacks-must-essentials-jiu-jitsu",
  "/bjj-hair-hairstyles-jiu-jitsu",
  "/bjj-in-kingston-upon-thames",
  "/bjj-jiu-jitsu",
  "/bjj-off-mats-live-jiu-jitsu-lifestyle",
  "/bjj-survival-guide-tips-tricks-training-jiu-jitsu",
  "/bjj-technique-straight-armbar-from-guard",
  "/bjj-throws-and-takedowns-concept",
  "/black-belt-blueprint-giveaway-rules",
  "/brazilian-jiu-jitsu-belt-system",
  "/brazilian-jiu-jitsu-body-awareness",
  "/brazilian-jiu-jitsu-concept-concept-top-and-bottom-centre",
  "/brazilian-jiu-jitsu-is-a-way-of-life",
  "/brazilian-jiu-jitsu-moves",
  "/brazilian-jiu-jitsu-seminars",
  "/brazilian-jiu-jitsu-techniques",
  "/brazilian-jiu-jitsu-techniques-grips",
  "/brazilian-jiu-jitsu-tips-a-c-t-model",
  "/brazilian-jiu-jitsu-tips-posture",
  "/brazilian-jiu-jitsu-training-animals",
  "/brazilian-jiu-jitsu-video",
  "/brazilian-jiu-jitsu-video-breathing",
  "/brazilian-jiu-jitsu-video-chokes",
  "/brazilian-jiu-jitsu-video-interview",
  "/cant-find-that",
  "/check-your-email",
  "/collections/adam-r-stacey",
  "/collections/bags",
  "/collections/bjj-books-and-videos",
  "/collections/books",
  "/collections/concepts",
  "/collections/conditioning-and-recovery",
  "/collections/kit-dale",
  "/collections/leg-locks",
  "/collections/leigh-remedios",
  "/collections/masterclass-series",
  "/collections/miad-najafi",
  "/collections/mike-bidwell",
  "/collections/nic-gregoriades",
  "/collections/oli-geddes",
  "/collections/peter-lakatos",
  "/collections/seminars",
  "/collections/stickers",
  "/collections/videos",
  "/collections/yiyang-ng",
  "/conceptual-jiu-jitsu-at-its-finest",
  "/coordinate-movement-and-breathing",
  "/cross-choke-from-mount",
  "/different-approach-side-control",
  "/dont-quit-at-blue-belt",
  "/ep-045-martin-lowe",
  "/ep-046-masterskya",
  "/ep-047-brad-waldron",
  "/ep-048-pedro-sauer",
  "/ep-051-jay-valko",
  "/ep-052-mike-velez",
  "/ep-053-paul-moran-2",
  "/ep-054-nogi-yogi",
  "/ep-055-daren-bartlett",
  "/ep-056-bret-perchaluk",
  "/ep-058-brent-burniston",
  "/ep-058-james-hoffman",
  "/ep-059-ishmael-bentley",
  "/ep-060-mike-pastor",
  "/ep-061-jay-campbell",
  "/ep-062-lawrence-dunning",
  "/ep-063-thomas-mietz",
  "/ep-064-christopher-odell",
  "/ep-065-stuart-cooper",
  "/ep-066-scott-smith",
  "/ep-067-dr-john-bonner",
  "/ep-068-michael-katilus",
  "/ep-49-christopher-reed",
  "/ep-50-paul-bridges",
  "/episode-001-roy-dean",
  "/episode-002-mike-bidwell",
  "/episode-003-nick-raphael",
  "/episode-004-eddie-fyvie",
  "/episode-005-paul-moran",
  "/episode-006-mike-arash-moghaddas",
  "/episode-007-liam-resnekov",
  "/episode-008-david-reilly",
  "/episode-009-chris-matakas",
  "/episode-010-matt-thornton",
  "/episode-011-scott-langley",
  "/episode-012-roger-gracie",
  "/episode-013-billy-biohazard-graziadei",
  "/episode-014-daniel-strauss",
  "/episode-015-budo-jake-mcgee",
  "/episode-016-nathan-raaths",
  "/episode-017-johnny-fd",
  "/episode-018-cyrille-diabate",
  "/episode-019-josh-griffiths",
  "/episode-020-alexander-darwin",
  "/episode-021-rich-byrne",
  "/episode-022-roy-dean-2",
  "/episode-023-liam-resnekov-2",
  "/episode-025-kit-dale",
  "/episode-026-manuel-flores",
  "/episode-027-andrew-macdonald",
  "/episode-028-henry-akins",
  "/episode-029-simon-yeo",
  "/episode-030-rondel-benjamin",
  "/episode-031-oliver-geddes",
  "/episode-032-huntley-smith",
  "/episode-033-gerald-garland",
  "/episode-034-brian-jones",
  "/episode-035-chuck-rylant",
  "/episode-036-robert-drysdale",
  "/episode-037-ryan-ford",
  "/episode-038-jason-keaton",
  "/episode-039-fernando-yamasaki",
  "/episode-040-jon-hinds",
  "/episode-041-david-aguzzi",
  "/episode-042-daniele-boleli",
  "/episode-043-adem-redzovic",
  "/episode-044-heather-raftery",
  "/episode-24-abraham-marte",
  "/exclusive-video-detailed-triangle-choke-explanation",
  "/favorite-sweep-part-2",
  "/favorite-sweep-part-one",
  "/finding-your-flow-in-jiu-jitsu-2",
  "/flow-diagrams-for-brazilian-jiu-jitsu",
  "/flow-drill-for-jiu-jitsu",
  "/grapple-with-your-eyes-closed",
  "/grappling-central-podcast",
  "/high-percentage-side-mount-escape",
  "/high-percentage-straight-foot-lock-set-up",
  "/hips-and-elbows-concept",
  "/how-many-takedowns-do-you-really-need",
  "/how-to-pass-the-de-la-riva-guard",
  "/important-concept-jiu-jitsu",
  "/introduction-jiu-jitsu-photography",
  "/is-jiu-jitsu-a-cult",
  "/is-your-neck-strong-enough-for-jiu-jitsu",
  "/its-not-about-how-hard-you-can-roll",
  "/jiu-jitsu-40",
  "/jiu-jitsu-and-mma-workouts",
  "/jiu-jitsu-concept-combining-masses",
  "/jiu-jitsu-concept-head-and-eye-movement",
  "/jiu-jitsu-concept-powerpoint-base",
  "/jiu-jitsu-concept-using-a-first-class-lever",
  "/jiu-jitsu-flow-drill-techniques",
  "/jiu-jitsu-is-good-for-you",
  "/jiu-jitsu-is-meditation",
  "/jiu-jitsu-journal-taking-notes-bjj",
  "/jiu-jitsu-life-lessons",
  "/jiu-jitsu-masterclass",
  "/jiu-jitsu-side-mount",
  "/jiu-jitsu-sisterhood-selfie-scavenger-hunt",
  "/jiu-jitsu-takedown-drill",
  "/jiu-jitsu-the-perfect-sport-for-kids",
  "/jiu-jitsu-video-powerful-closed-guard-sweep",
  "/jiu-jitsu-with-no-hands",
  "/journey-into-jiu-jitsu",
  "/juicing-for-bjj-mma",
  "/kettlebell-training-for-jiu-jitsu",
  "/keys-to-improve-your-mount",
  "/kimura-sweep-submission",
  "/meditation-martial-arts",
  "/membership-access",
  "/morning-routine-bjj-day",
  "/my-journey-into-martial-arts",
  "/nobody-can-take",
  "/nutrient-timing-for-grapplers",
  "/nutrition-for-jiu-jitsu-4",
  "/overtraining-in-jiu-jitsu",
  "/pages/cant-find-that",
  "/pages/check-your-email",
  "/pages/closed-bjj-building-blocks-and-bjj-learning-sites",
  "/pages/closed-jiu-jitsu-master-academy",
  "/pages/jiu-jitsu-training-secrets",
  "/pages/sign-up-thank-you",
  "/pages/thank-you",
  "/pages/thank-you-1",
  "/pages/thank-you-for-your-purchase",
  "/pages/your-discount-coupon",
  "/palawan",
  "/passing-the-guard-a-conceptual-approach",
  "/performance-enhancing-drugs-jiu-jitsu",
  "/period-training-jiu-jitsu-menstrual-cycle-martial-arts",
  "/policies/shipping-policy",
  "/positional-study-shin-to-shin-guard",
  "/post-training-shake-for-brazilian-jiu-jitsu",
  "/products/astrum-rashguard",
  "/products/beyond-the-black-belt-digital-download",
  "/products/copy-of-grapplers-longevity-vol-2-digital-download",
  "/products/copy-of-leg-locks-demystified",
  "/products/copy-of-musashi-limited-edition",
  "/products/musashi-limited-edition",
  "/products/tail-eater-back-pack",
  "/products/the-seeker-t-shirt",
  "/rules-bjj-grappling-competitions",
  "/sign-up-thank-you",
  "/special-episode-mike-bidwell-2",
  "/special-episode-nic-gregoriades-ama",
  "/ten-essential-supplements-for-jiu-jitsu-fighters",
  "/thank-you",
  "/the-best-yoga-posture-for-bjj",
  "/the-biggest-lie-in-jiu-jitsu",
  "/the-essence-of-jiu-jitsu",
  "/the-fundamentals-of-x-guard",
  "/the-sneakiest-choke-youll-ever-do",
  "/the-soul-of-jiu-jitsu",
  "/the-spirit-of-jiu-jitsu",
  "/the-ultimate-side-control-attack",
  "/the-weakness-hiding-in-your-jiu-jitsu",
  "/there-are-no-bad-positions-in-jiu-jitsu",
  "/top-10-superfoods-jiu-jitsu",
  "/top-ten-bjj-vacation-cities",
  "/training-martial-arts-moms",
  "/want-open-jiu-jitsu-academy",
  "/what-makes-a-true-jiu-jitsu-master",
  "/why-i-do-jiu-jitsu",
  "/why-you-lost-your-last-jiu-jitsu-tournament",
];

export const inventoryPreserve: string[] = [
  "/",
  "/blogs/articles",
  "/blogs/blog",
  "/blogs/blog/10-000-hours-just-start",
  "/blogs/blog/10-reasons-your-jiu-jitsu-isnt-getting-better",
  "/blogs/blog/1912-jiu-jitsu-demo-the-roots-of-bjj",
  "/blogs/blog/5-tips-to-instantly-improve-your-guard",
  "/blogs/blog/5-ways-jiujitsu-benefits-children-autism",
  "/blogs/blog/6-tips-for-older-jiu-jitsu-players",
  "/blogs/blog/a-brief-history-of-bjj",
  "/blogs/blog/a-coach-is-more-than-just-a-teacher",
  "/blogs/blog/a-deeper-understanding-of-jiu-jitsu",
  "/blogs/blog/a-glossary-of-bjj-terms",
  "/blogs/blog/a-goodbye-to-my-friend-oli-geddes",
  "/blogs/blog/a-jiu-jitsu-experience",
  "/blogs/blog/are-you-overtraining-in-jiu-jitsu",
  "/blogs/blog/attending-your-first-jiu-jitsu-class",
  "/blogs/blog/back-pain-and-jiu-jitsu",
  "/blogs/blog/become-a-master-of-escapes",
  "/blogs/blog/bjj-and-grappling-skin-infections-part-1-ringworm",
  "/blogs/blog/bjj-and-grappling-skin-infections-part-2-staph-and-impetigo",
  "/blogs/blog/bjj-and-grappling-skin-infections-part-3-herpes-gladiatorum",
  "/blogs/blog/bjj-over-40-50-beyond-tips-for-older-grapplers",
  "/blogs/blog/bjj-strength-blitz-game-changing-workout",
  "/blogs/blog/bjjs-biggest-weakness-is-its-new-secret-weapon",
  "/blogs/blog/brazilian-jiu-jitsu-competitions",
  "/blogs/blog/caffeine-jiu-jitsu",
  "/blogs/blog/can-jiu-jitsu-athletes-benefit-from-the-ecological-method-a-coachs-perspective",
  "/blogs/blog/cauliflower-ears-in-jiu-jitsu",
  "/blogs/blog/choosing-the-right-bjj-academy-for-you",
  "/blogs/blog/control-your-breathing",
  "/blogs/blog/cross-training-in-wrestling-and-jiu-jitsu",
  "/blogs/blog/cut-weight-jiu-jitsu-competitions",
  "/blogs/blog/dealing-with-injuries-in-jiu-jitsu",
  "/blogs/blog/do-you-know-who-invented-these-bjj-techniques",
  "/blogs/blog/eddie-bravo-a-jiu-jitsu-original",
  "/blogs/blog/family-jiu-jitsu",
  "/blogs/blog/fear-and-courage",
  "/blogs/blog/first-it-s-an-art",
  "/blogs/blog/five-ways-to-naturally-boost-your-immune-system",
  "/blogs/blog/gi-or-no-gi",
  "/blogs/blog/grappling-martial-arts",
  "/blogs/blog/gripping-and-hand-issues-in-jiu-jitsu",
  "/blogs/blog/helio-gracies-big-concern",
  "/blogs/blog/how-to-drop-body-fat",
  "/blogs/blog/how-to-learn-jiu-jitsu-faster",
  "/blogs/blog/how-to-overcome-low-back-pain-in-brazilian-jiu-jitsu",
  "/blogs/blog/how-to-roll-as-an-older-grappler-without-breaking-yourself",
  "/blogs/blog/how-to-train-leg-locks-safely",
  "/blogs/blog/if-sambo-was-easy-it-would-be-called-jiu-jitsu",
  "/blogs/blog/importance-footwork-jiu-jitsu",
  "/blogs/blog/important-tips-for-beginners",
  "/blogs/blog/jiu-jitsu-better-dieting",
  "/blogs/blog/jiu-jitsu-mat-etiquette",
  "/blogs/blog/jiu-jitsu-vs-karate",
  "/blogs/blog/joint-locks-in-jiu-jitsu",
  "/blogs/blog/just-what-are-fundamentals",
  "/blogs/blog/law-strength-training",
  "/blogs/blog/leg-locks-101",
  "/blogs/blog/main-positions-jiu-jitsu",
  "/blogs/blog/martial-arts-styles",
  "/blogs/blog/mauricio-gomes-the-legacy-of-a-jiu-jitsu-pioneer",
  "/blogs/blog/mauricios-advice-when-you-are-currently-unable-to-train",
  "/blogs/blog/mobility-training-for-jiu-jitsu",
  "/blogs/blog/my-journey-into-footlocks",
  "/blogs/blog/myths-and-misunderstandings-about-fat-loss",
  "/blogs/blog/no-bad-positions-in-jiu-jitsu",
  "/blogs/blog/no-you-didnt-start-jiu-jitsu-too-late",
  "/blogs/blog/pareto-principle-for-jiu-jitsu",
  "/blogs/blog/passivity-as-a-tool-for-self-defence",
  "/blogs/blog/physical-health-and-fitness-benefits-of-brazilian-jiu-jitsu",
  "/blogs/blog/positional-hierarchy-and-strategy",
  "/blogs/blog/positional-sparring-in-brazilian-jiu-jitsu-the-key-to-mastery",
  "/blogs/blog/positional-study-shin-to-shin-single-leg-x-ashi-garami",
  "/blogs/blog/preparing-for-the-podium-a-beginner-s-guide-to-bjj-rules",
  "/blogs/blog/protect-and-heal-your-neck-in-jiu-jitsu",
  "/blogs/blog/reflections-on-my-early-days",
  "/blogs/blog/return-of-the-long-lost-gracie-gold-medal",
  "/blogs/blog/rib-injuries-in-jiu-jitsu",
  "/blogs/blog/rickson-gracie-jiu-jitsus-living-legend",
  "/blogs/blog/roger-gracie",
  "/blogs/blog/roger-gracies-father-sparring-aged-64",
  "/blogs/blog/rolls-gracie-vs-rickson-gracie",
  "/blogs/blog/rolls-rickson-renzo-or-roger-gracie-who-was-the-best",
  "/blogs/blog/should-you-train-bjj-when-youre-sick-doctor-and-black-belt-explains",
  "/blogs/blog/sleep-and-the-jiu-jitsu-practitioner",
  "/blogs/blog/spring-super-seminar",
  "/blogs/blog/stronger-healthier-shoulders-for-jiu-jitsu",
  "/blogs/blog/summer-seaside-special",
  "/blogs/blog/taking-inspiration-from-helvecio-penna",
  "/blogs/blog/the-art-of-verbal-jiu-jitsu",
  "/blogs/blog/the-doctor-who-quit-medicine-to-teach-jiu-jitsu",
  "/blogs/blog/the-evolution-of-jiu-jitsu",
  "/blogs/blog/the-first-mma-match-caught-on-film",
  "/blogs/blog/the-gracies-first-family-of-jiu-jitsu",
  "/blogs/blog/the-history-of-brazilian-jiu-jitsu",
  "/blogs/blog/the-mauricio-gomes-chronicles-part-1",
  "/blogs/blog/the-mauricio-gomes-chronicles-part-2",
  "/blogs/blog/the-mauricio-gomes-chronicles-part-3",
  "/blogs/blog/the-neck-grappling-arts-and-tech-devices",
  "/blogs/blog/the-one-supplement-all-jiu-jitsu-athletes-should-take",
  "/blogs/blog/the-rear-naked-choke-the-king-of-submissions",
  "/blogs/blog/the-science-of-jiu-jitsu",
  "/blogs/blog/the-single-leg-takedown-a-conceptual-approach",
  "/blogs/blog/the-story-of-rolls-gracie-and-bob-anderson",
  "/blogs/blog/the-surprising-health-benefits-of-strength-training",
  "/blogs/blog/the-tokugawa-gi-story",
  "/blogs/blog/the-top-7-shoulder-conditions-effecting-grapplers",
  "/blogs/blog/the-world-of-grappling-an-a-z-tour-of-wrestling-arts",
  "/blogs/blog/top-5-injury-prevention-stretches-for-jiu-jitsu",
  "/blogs/blog/understanding-takedowns-in-jiu-jitsu",
  "/blogs/blog/using-heart-rate-variability-to-monitor-your-training",
  "/blogs/blog/using-your-minds-eye-visualization-for-jiu-jitsu",
  "/blogs/blog/vintage-newaza-footage-from-1949",
  "/blogs/blog/what-it-really-takes-to-earn-a-bjj-black-belt",
  "/blogs/blog/what-kit-and-equipment-will-you-need-for-bjj",
  "/blogs/blog/why-concepts-are-better-than-techniques-in-bjj",
  "/blogs/blog/why-discipline-not-insight-changes-a-life",
  "/blogs/blog/why-every-generation-thinks-jiu-jitsu-has-changed-for-the-worse",
  "/blogs/blog/why-jiu-jitsu-was-the-therapy-i-didn-t-know-i-needed",
  "/blogs/blog/why-learn-heel-hooks",
  "/blogs/blog/why-low-carb-diet-is-bullsh-t",
  "/blogs/blog/why-you-should-compete-at-least-once-in-bjj",
  "/blogs/blog/wrestling-takedowns",
  "/blogs/blog/yoga-jiu-jitsu-a-natural-symbiosis",
  "/blogs/news",
  "/blogs/podcast",
  "/blogs/techniques",
  "/blogs/techniques/a-simple-half-guard-back-take",
  "/blogs/techniques/a-system-for-guard-passing",
  "/blogs/techniques/basic-choke-from-lapel-guard",
  "/blogs/techniques/battle-for-the-underhook",
  "/blogs/techniques/bear-hug-defence-1",
  "/blogs/techniques/bear-hug-defence-2",
  "/blogs/techniques/bear-hug-defence-3",
  "/blogs/techniques/bear-hug-defence-4",
  "/blogs/techniques/bear-hug-defence-5",
  "/blogs/techniques/bow-arrow-countered-here-s-the-fix",
  "/blogs/techniques/butterfly-guard-passing-tips",
  "/blogs/techniques/closed-guard-omoplata-fundamentals",
  "/blogs/techniques/collar-and-sleeve-guard-troubleshooting-and-entry",
  "/blogs/techniques/collar-choke-from-the-arm-wrap",
  "/blogs/techniques/collar-grip-to-ankle-pick",
  "/blogs/techniques/countering-the-backstep",
  "/blogs/techniques/cutting-armbar-from-the-arm-wrap",
  "/blogs/techniques/de-la-riva-to-sit-up-guard-3-easy-sweeps",
  "/blogs/techniques/don-t-get-leg-locked",
  "/blogs/techniques/false-reap-entry-to-heel-hook-leigh-remedios-polaris-finish",
  "/blogs/techniques/fix-your-lapel-guard-choke",
  "/blogs/techniques/free-lasso-sweep",
  "/blogs/techniques/gi-meets-no-gi-the-ghost-escape",
  "/blogs/techniques/gripping-strategies-for-bjj",
  "/blogs/techniques/half-guard-ankle-hook-sweep",
  "/blogs/techniques/heel-hook-details-leigh-remedios",
  "/blogs/techniques/high-percentage-judo-takedowns-for-bjj",
  "/blogs/techniques/how-to-defend-heel-hooks-and-why-it-makes-your-offence-better",
  "/blogs/techniques/inside-vs-outside-heel-hooks-which-is-stronger",
  "/blogs/techniques/knee-slice-passing-tips",
  "/blogs/techniques/lapel-guard-to-gubber-guard-high-percentage-chokes",
  "/blogs/techniques/limp-arm-back-take",
  "/blogs/techniques/michael-myers-guard-passing",
  "/blogs/techniques/old-school-self-defence-with-mauricio-gomes",
  "/blogs/techniques/oliver-geddes-his-go-to-half-guard-pass",
  "/blogs/techniques/oliver-geddes-teaches-the-ezekiel-choke-from-arm-triangle",
  "/blogs/techniques/oliver-geddes-teaches-the-s-grip-arm-triangle",
  "/blogs/techniques/omoplata-roll-escape-counter-maintaining-control",
  "/blogs/techniques/open-guard-fundamentals-with-leigh-remedios",
  "/blogs/techniques/posture-control-choke",
  "/blogs/techniques/powerful-choke-from-gubber-guard",
  "/blogs/techniques/pressure-and-patience-are-vital",
  "/blogs/techniques/rob-taylor-s-guard-passing-masterclass",
  "/blogs/techniques/roll-under-sweep-from-half-guard",
  "/blogs/techniques/setting-up-gubber-guard",
  "/blogs/techniques/simple-tip-to-massively-improve-your-chokes",
  "/blogs/techniques/smooth-side-control-to-mount-transition",
  "/blogs/techniques/sumi-gaeshi-corner-reversal",
  "/blogs/techniques/terminator-guard-passing",
  "/blogs/techniques/the-arm-wrap-system",
  "/blogs/techniques/the-complete-underhook-half-guard-system-sweeps-back-takes",
  "/blogs/techniques/the-de-la-riva-balloon-sweep-made-easy",
  "/blogs/techniques/the-invisible-collar-choke",
  "/blogs/techniques/the-leg-weave-pass",
  "/blogs/techniques/the-tornado-throw",
  "/blogs/techniques/triangle-choke-from-the-arm-wrap",
  "/blogs/techniques/tripod-sweep-from-the-jelly-guard",
  "/blogs/techniques/unlocking-turtle-position-3-effective-turnovers",
  "/blogs/techniques/using-kazushi-to-hit-the-ankle-pick",
  "/blogs/techniques/what-is-a-heel-hook",
  "/blogs/techniques/yoko-tomoe-nage",
  "/blogs/videos",
  "/cart",
  "/collections",
  "/collections/all",
  "/collections/apparel",
  "/collections/belts",
  "/collections/featured",
  "/collections/gis",
  "/collections/hoodies",
  "/collections/mushashi-collection",
  "/collections/patches",
  "/collections/rash-guards",
  "/collections/shorts",
  "/collections/sisterhood",
  "/collections/spats",
  "/collections/t-shirts",
  "/collections/training-gear",
  "/pages/about",
  "/pages/armed-forces",
  "/pages/beginners-guide-to-bjj-signup",
  "/pages/blog",
  "/pages/contact",
  "/pages/disclaimer",
  "/pages/how-to-suck-less-at-jiu-jitsu",
  "/pages/jiu-jitsu-brotherhood-club-network",
  "/pages/oli-geddes-foundation-charity-event-kingston-jiu-jitsu",
  "/pages/privacy-policy",
  "/pages/progression-the-belt-system",
  "/pages/spring-super-seminar",
  "/pages/summer-seaside-special",
  "/pages/terms-conditions",
  "/pages/the-oliver-geddes-foundation",
  "/pages/welsh-winter-special",
  "/products/2nd-summer-seaside-special-super-seminar",
  "/products/astrum-gi",
  "/products/beast-mode-rashguard",
  "/products/classic-embroidered-badge",
  "/products/enso-4-0-gi-black",
  "/products/enso-4-0-gi-blue",
  "/products/enso-4-0-gi-white",
  "/products/evolver-classic",
  "/products/evolver-classic-red",
  "/products/face-your-fears-rashguard",
  "/products/fight-shorts",
  "/products/future-stars-gi-blue",
  "/products/history-on-fire-t-shirt",
  "/products/jiu-jitsu-brotherhood-club-network-adults-competition",
  "/products/journey-bjj-belt",
  "/products/kids-club-network-interclub-competition-2024",
  "/products/kids-club-network-interclub-competition-2026",
  "/products/open-source-jiu-jitsu-hooded-sweatshirt-gray",
  "/products/open-source-jiu-jitsu-hooded-sweatshirt-red",
  "/products/signature-series-hooded-sweatshirt",
  "/products/sisterhood-mini-patch",
  "/products/sisterhood-rashguard",
  "/products/stand-up-eight-t-shirt-black",
  "/products/summer-super-seminar-2025",
  "/products/tail-eater-back-patch",
  "/products/tail-eater-rashguard-blue-trim",
  "/products/tail-eater-rashguard-classic-black",
  "/products/the-gentle-art-rashguard",
  "/products/the-musashi-spats",
  "/products/the-oni-gi",
  "/products/the-tokugawa-gi",
  "/search",
];

export const queryMigrations: Array<{
  param: string;
  value: string;
  action: "301" | "410";
  destination: string | null;
}> = [
  {
    "param": "page_id",
    "value": "4958",
    "action": "301",
    "destination": "/pages/beginners-guide-to-bjj-signup"
  },
  {
    "param": "page_id",
    "value": "5157",
    "action": "301",
    "destination": "/pages/beginners-guide-to-bjj-signup"
  },
  {
    "param": "p",
    "value": "4942",
    "action": "410",
    "destination": null
  },
  {
    "param": "p",
    "value": "5110",
    "action": "410",
    "destination": null
  },
  {
    "param": "p",
    "value": "5030",
    "action": "410",
    "destination": null
  },
  {
    "param": "p",
    "value": "5246",
    "action": "410",
    "destination": null
  },
  {
    "param": "p",
    "value": "5257",
    "action": "410",
    "destination": null
  }
];
